openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASA Homework enroll
  description: |-
    The application is collecting students information (student ID, name, repository URL) and it is providing an SSH key
    that the student should configure in their repository.
  version: 1.0.0
paths:
  /enroll/:
    post:
      tags: ["General"]
      operationId: enrollStudent
      summary: Enroll a new student in the system, and provides the public key.
      description: |-
        This endpoint receives the information about the student to enroll, generates a new SSH key pair and return the
        public key.
        If the user is already enrolled, this method returns an error.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentEnrollRequest"
      responses:
        "200":
          description: Student enrolled successfully, public key returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentEnrollResult"
        "409":
          description: The user is already enrolled, cannot proceed
        "400": { $ref: "#/components/responses/BadRequest" }
        "500": { $ref: "#/components/responses/InternalServerError" }

components:
  schemas:
    StudentEnrollRequest:
      title: Student enroll form data
      type: object
      properties:
        studentId:
          type: integer
          minimum: 1
          maximum: 9999999
          example: 1234567
        firstName:
          type: string
          pattern: ^.*?$
          minLength: 2
          maxLength: 32
          example: John
        lastName:
          type: string
          pattern: ^.*?$
          minLength: 2
          maxLength: 32
          example: Doe
        email:
          type: string
          format: email
          pattern: "@studenti\\.uniroma1\\.it$"
          minLength: 25
          maxLength: 50
          example: doe.1234567@studenti.uniroma1.it
        repoUrl:
          type: string
          format: url
          pattern: "^(ssh://)?git@.*"
          minLength: 5
          maxLength: 50
          example: git@github.com:yourname/yourrepo.git

    StudentEnrollResult:
      title: Student enroll response
      type: object
      properties:
        publicKey:
          type: string
          minLength: 20
          maxLength: 200
          example: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ1pP7eWBFEMmf494e10G2242GoWB/pz6g3MO62Twpgy"

  responses:
    BadRequest:
      description: The request was not compliant with the documentation (eg. missing fields, etc)
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs
