openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASA Homework enroll
  description: |-
    The application is collecting students information (student ID, name, repository URL) and it is providing an SSH key
    that the student should configure in their repository.
  version: 1.0.0
paths:
  /enroll/:
    post:
      tags: ["Enrollment"]
      operationId: enrollStudent
      summary: Enroll a new student in the system, and provides the public key.
      description: |-
        This endpoint receives the information about the student to enroll, generates a new SSH key pair and return the
        public key.
        If the user is already enrolled, this method returns an error.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentEnrollRequest"
      responses:
        "200":
          description: Student enrolled successfully, public key returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentEnrollResult"
        "409":
          description: The user is already enrolled, cannot proceed
        "400": { $ref: "#/components/responses/BadRequest" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /results/:
    get:
      tags: [ "Results" ]
      operationId: listResults
      summary: Return the list of all students with their results
      description: |-
        Return a list of result object.
        Objects contain the result of the homework validation for each student.
      responses:
        "200":
          description: List retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultList"
        "500": { $ref: "#/components/responses/InternalServerError" }

  /results/{studentId}/git:
    get:
      tags: [ "Results" ]
      operationId: getGitLog
      summary: Return the log for Git actions
      description: |-
        Return the output of Git commands that were used to clone the repository.
      responses:
        "200":
          description: Git log
          content:
            text/plain: {}
        "404": { $ref: "#/components/responses/ResultNotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /results/{studentId}/openapi:
    get:
      tags: [ "Results" ]
      operationId: getOpenAPILog
      summary: Return the reason for OpenAPI score
      description: |-
        Return a descriptive text for the OpenAPI score.
      responses:
        "200":
          description: OpenAPI score log
          content:
            text/plain: {}
        "404": { $ref: "#/components/responses/ResultNotFound" }
        "500": { $ref: "#/components/responses/InternalServerError" }

components:
  schemas:
    StudentEnrollRequest:
      title: Student enroll form data
      type: object
      properties:
        studentID:
          type: integer
          minimum: 1
          maximum: 9999999
          example: 1234567
        firstName:
          type: string
          pattern: ^.*?$
          minLength: 2
          maxLength: 32
          example: John
        lastName:
          type: string
          pattern: ^.*?$
          minLength: 2
          maxLength: 32
          example: Doe
        email:
          type: string
          format: email
          pattern: "@studenti\\.uniroma1\\.it$"
          minLength: 25
          maxLength: 70
          example: doe.1234567@studenti.uniroma1.it
        repoURL:
          type: string
          format: url
          pattern: "^(ssh://)?git@.*"
          minLength: 5
          maxLength: 200
          example: git@github.com:yourname/yourrepo.git

    StudentEnrollResult:
      title: Student enroll response
      type: object
      properties:
        publicKey:
          type: string
          minLength: 20
          maxLength: 200
          example: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ1pP7eWBFEMmf494e10G2242GoWB/pz6g3MO62Twpgy"

    ResultList:
      title: List of homework results
      type: array
      items:
        type: object
        properties:
          studentID:
            type: integer
            minimum: 1
            maximum: 9999999
            example: 1234567
          hash:
            type: string
            example: abcdef012345
            pattern: ^[a-fA-F0-9]+$
            maxLength: 50
            minLength: 5
          openapi:
            type: integer
            minimum: 0
            maximum: 30
            example: 18
          go:
            type: integer
            minimum: 0
            maximum: 30
            example: 18
          vue:
            type: integer
            minimum: 0
            maximum: 30
            example: 18
          docker:
            type: integer
            minimum: 0
            maximum: 30
            example: 18
          lastcheck:
            type: string
            format: date-time
            example: 2020-01-03T16:12:58Z
            pattern: ^[0-9:A-Z-]$


  responses:
    ResultNotFound:
      description: The requested result has not been found.
    BadRequest:
      description: The request was not compliant with the documentation (eg. missing fields, etc)
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs
